import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';


const SECTIONS = [
  { id: 'electronic-platform', title: '1. Electronic Platform' },
  { id: 'acceptance-of-terms', title: '2. Acceptance of Terms' },
  { id: 'definitions', title: '3. Definitions' },
  { id: 'user-account', title: '4. User Account' },
  { id: 'services', title: '5. Services' },
  { id: 'ads-links', title: '6. Ads & Links' },
  { id: 'crm', title: '7. Customer Relations' },
  { id: 'payment-terms', title: '8. Payment Terms' },
  { id: 'cancellation-refund', title: '9. Cancellation & Refund' },
  { id: 'liability-limitation', title: '10. Liability' },
  { id: 'intellectual-property', title: '11. Intellectual Property' },
  { id: 'user-conduct', title: '12. User Conduct' },
  { id: 'termination', title: '13. Termination' },
  { id: 'data-privacy', title: '14. Data Privacy' },
  { id: 'governing-law', title: '15. Governing Law' },
  { id: 'contact-us', title: '16. Contact Us' }
];

function TermsOfUse() {
  const [activeSection, setActiveSection] = useState('electronic-platform');

  useEffect(() => {
    window.scrollTo(0, 0);

    const handleScroll = () => {
      const scrollPosition = window.scrollY + 100;
      for (const section of SECTIONS) {
        const element = document.getElementById(section.id);
        if (element) {
          const offsetTop = element.offsetTop;
          const height = element.offsetHeight;
          if (scrollPosition >= offsetTop && scrollPosition < offsetTop + height) {
            setActiveSection(section.id);
          }
        }
      }
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const scrollToSection = (id: string) => {
    const element = document.getElementById(id);
    if (element) {
      window.scrollTo({
        top: element.offsetTop - 100,
        behavior: 'smooth'
      });
    }
  };

  return (
    <div className="min-h-screen bg-white">
      

      {/* Hero Section */}
      <div className="pt-32 pb-16 bg-neutral-50 border-b border-gray-100">
        <div className="max-w-7xl mx-auto px-6 md:px-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
          >
            <h1 className="text-4xl md:text-6xl font-black text-gray-900 tracking-tighter mb-4">
              Terms & Conditions
            </h1>
            <p className="text-gray-400 font-medium text-lg italic tracking-widest uppercase">Eleqt Holidays & Leisure • Legal Agreement</p>
          </motion.div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 md:px-10 py-24 relative">
        <div className="flex flex-col lg:flex-row gap-20">

          {/* Sticky Sidebar ToC (Desktop Only) */}
          <aside className="hidden lg:block w-72 sticky top-32 h-fit">
            <nav className="space-y-1">
              <p className="text-[10px] font-bold uppercase tracking-[0.3em] text-amber-700 mb-8">Navigation</p>
              {SECTIONS.map((section) => (
                <button
                  key={section.id}
                  onClick={() => scrollToSection(section.id)}
                  className={`block w-full text-left py-2.5 text-xs font-bold transition-all border-l-2 pl-6 ${activeSection === section.id
                    ? 'border-amber-600 text-amber-700 bg-amber-50/50'
                    : 'border-transparent text-gray-400 hover:text-gray-900 hover:border-gray-200'
                    }`}
                >
                  {section.title}
                </button>
              ))}
            </nav>
          </aside>

          {/* Main Content */}
          <main className="flex-1 max-w-4xl">
            <motion.div 
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 1, delay: 0.2 }}
              className="space-y-12"
            >
              
              <div className="pb-12 border-b border-gray-100">
                <p className="text-gray-700 leading-8 text-[17px] font-light">
                  This document is an electronic record in accordance with the provisions of the Information Technology Act, 2000, and rules thereunder. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
              </div>

              {/* 1. ELECTRONIC PLATFORM */}
              <section id="electronic-platform" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">1. ELECTRONIC PLATFORM:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <p className="text-gray-700 leading-8 text-[17px] font-light">
                  The domain name [eleqtholidays.in] ("Website") and the mobile application ("Application") are owned and operated by M/s Psynuxsoftware Private Limited, a company incorporated under the Companies Act, 2013 ("Eleqt Holidays & Leisure" or “Eleqt” or "Company").
                </p>
              </section>

              <hr className="border-gray-100" />

              {/* 2. ACCEPTANCE OF TERMS */}
              <section id="acceptance-of-terms" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">2. ACCEPTANCE OF TERMS:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>
                    2.1 These Terms and Conditions ("Terms") constitute a legally binding agreement between the User ("You") and Eleqt. By accessing the Website, registering on the Application, or using any of the services provided by Eleqt ("Services"), you agree to be bound by these Terms.
                  </p>
                  <p>
                    2.2 If you do not agree to these Terms, please refrain from using our Services.
                  </p>
                  <p>
                    2.3 Eleqt reserves the right to update or amend these Terms at any time. Continued use of the Platform after changes constitutes acceptance.
                  </p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 3. DEFINITIONS */}
              <section id="definitions" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">3. DEFINITIONS:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>3.1 "Account" means the User’s registered profile with Eleqt.</p>
                  <p>3.2 "Package” or "Booking" means the Holiday Package facilitated through the Eleqt.</p>
                  <p>3.3 "Holiday" means the Holiday Package offered under Eleqt services.</p>
                  <p>3.4 "Total Package Fee" includes Airfare/ Rail fare, Hotel stay, Meal plans, Transfer & Sightseeing Cabs, Applicable taxes, Toll duty, Parking, Visa fees (if required), and Convenience fees. Or “Customized requirement demanded by You”</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 4. USER ACCOUNT & ELIGIBILITY */}
              <section id="user-account" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">4. USER ACCOUNT & ELIGIBILITY:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>4.1 Users must be 18+ years old and legally eligible to use services.</p>
                  <p>4.2 Users must provide accurate personal information, including name, mobile number, and payment details.</p>
                  <p>4.3 Users are responsible for the confidentiality of their login credentials.</p>
                  <p>4.4 As part of the registration process, you agree to receive such marketing and promotional materials via mail, SMS, and/or email as we may deem appropriate to send you in connection with our Website and Services. For further details relating to the same, please refer to our Privacy Policy.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 5. SERVICES */}
              <section id="services" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">5. SERVICES:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>5.1 Eleqt provides users with the demanded services by booking hotels, cabs, and flights/ trains, restaurants and local tour guides for the total journey.</p>
                  <p>5.2 Tour packages are subject to the availability, location, and local conditions.</p>
                  <p>5.3 User agrees to: Use the service for lawful purposes, not damage the hotel/ cab or disturb the driver/ guides, and avoid misuse, harassment, or fraudulent activity.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 6. ADVERTISEMENT AND LINKS */}
              <section id="ads-links" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">6. ADVERTISEMENT AND LINKS:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>6.1 Eleqt may periodically send promotional emails, SMSs, or push notifications to the User about its Services.</p>
                  <p>6.2 Eleqt also reserves the right to reject or refuse any third-party service used by the User in conjunction with Eleqt's Electronic Media.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 7. CUSTOMER RELATIONSHIP MANAGEMENT */}
              <section id="crm" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">7. CUSTOMER RELATIONSHIP MANAGEMENT:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>
                    7.1 All issues, opinions, suggestions, questions, and feedback while availing of Eleqt's Services shall be communicated to us through the following email address: <span className="text-amber-700 font-bold">eleqtholidays@gmail.com</span>
                  </p>
                  <p>
                    7.2 Reporting of any issue needs to be within 7 (seven) days of the occurrence of the issue, failing which, such issue will not be addressed. The User agrees and acknowledges that any issues/complaints/grievances a User has must be communicated to Eleqt only through the Electronic Media or to the consumer helpdesk as stipulated in these Terms of Use of the Electronic Media and not on any other third-party platform/social media channels.
                  </p>
                  <p>7.3 The User shall be responsible and liable in respect of the wrongful allegation made and any issues posted on such other third-party platforms/social media.</p>
                  <p>7.4 Eleqt takes no liability for the inability to get back or respond to any complaints made or content posted by the User about Eleqt on other channels.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 8. PAYMENT TERMS */}
              <section id="payment-terms" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">8. PAYMENT TERMS:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>8.1 Users agree to pay the full fare as displayed or notified during the Booking.</p>
                  <p>8.2 Payments may be made via cash, UPI, cards, or integrated payment gateways.</p>
                  <p>8.3 Additional charges may apply for surcharges, location-specific costs, or damage.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 9. CANCELLATION & REFUND */}
              <section id="cancellation-refund" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">9. CANCELLATION & REFUND:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>9.1 Bookings may be cancelled before the tour starts; charges may apply for late cancellations.</p>
                  <p>9.2 Refunds, if applicable, will be processed to the original payment method.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 10. LIABILITY AND LIMITATION */}
              <section id="liability-limitation" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">10. LIABILITY AND LIMITATION:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>10.1 Eleqt is not responsible for delays caused by traffic, weather, mechanical failure, acts/ forces of nature, or other Force Majeure Events.</p>
                  <p>10.2 Eleqt is not liable for loss of personal belongings left in hotels, cabs & trains/ flights.</p>
                  <p>10.3 Our total liability is limited to the Total Package Fee for the disputed Tour.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 11. INTELLECTUAL PROPERTY */}
              <section id="intellectual-property" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">11. INTELLECTUAL PROPERTY:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-4 text-gray-700 leading-8 text-[17px] font-light">
                  <p>11.1 All content, trademarks, logos, and software on the Platform belong to Eleqt or its licensors.</p>
                  <p>11.2 Users may not reproduce, copy, modify, or distribute any content without permission.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 12. USER CONDUCT */}
              <section id="user-conduct" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">12. USER CONDUCT:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <ul className="space-y-4 text-gray-700 font-light list-disc pl-5 leading-8 text-[17px]">
                  <li>Maintain respectful behavior with the Travel Expert and support staff.</li>
                  <li>Do not smoke, drink alcohol, or carry illegal items during the tour.</li>
                  <li>Be responsible for their safety and conduct during the tour.</li>
                </ul>
              </section>

              <hr className="border-gray-100" />

              {/* 13. TERMINATION */}
              <section id="termination" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">13. TERMINATION:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <p className="text-gray-700 leading-8 text-[17px] font-light">
                  Eleqt may suspend or terminate a User’s account for violations of these Terms, fraudulent behavior, or misuse of services.
                </p>
              </section>

              <hr className="border-gray-100" />

              {/* 14. DATA PRIVACY */}
              <section id="data-privacy" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">14. DATA PRIVACY:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <p className="text-gray-700 leading-8 text-[17px] font-light">
                  Personal information is collected, stored, and used as per our <a href="/privacy-policy" className="text-amber-700 font-bold underline underline-offset-4">Privacy Policy</a>.
                </p>
              </section>

              <hr className="border-gray-100" />

              {/* 15. GOVERNING LAW AND DISPUTES */}
              <section id="governing-law" className="space-y-6 scroll-mt-32">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">15. GOVERNING LAW AND DISPUTES:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="space-y-6 text-gray-700 leading-8 text-[17px] font-light">
                  <p>15.1 These Terms are governed by the laws of India.</p>
                  <p>
                    15.2 All disputes arising out of or in connection with the Terms of Use shall be attempted to be settled through negotiation between senior management of the Company and the User. If any dispute arising between the parties is not amicably settled within a reasonable period of sixty (60) days of the initiation of the aforesaid dispute resolution mechanisms, then, the same shall be resolved by arbitration following the provisions of the Rules of Arbitration of the Indian Council of Arbitration for the time being in force, which rules shall be deemed to be incorporated by reference in this Clause (15). The dispute shall be referred to one (1) arbitrator to be appointed/ nominated by the Company. The language of the arbitration will be English. The decision of the arbitrator will be final, binding, and incontestable and may be used as a basis for judgment thereon in India or elsewhere. The Company and the User will bear their own costs of the arbitration.
                  </p>
                  <p>15.3 All disputes shall be subject to the jurisdiction of the courts in Bhubaneswar, Odisha.</p>
                </div>
              </section>

              <hr className="border-gray-100" />

              {/* 16. CONTACT US */}
              <section id="contact-us" className="space-y-6 scroll-mt-32 pb-20">
                <h2 className="text-2xl font-bold text-gray-900 tracking-tight">16. CONTACT US:</h2>
                <div className="w-12 h-0.5 bg-amber-600/30" />
                <div className="p-8 bg-neutral-900 text-white rounded-2xl shadow-xl space-y-4">
                  <p className="font-light">For questions or support, contact us at:</p>
                  <p className="text-xl font-bold tracking-tight">Email: <a href="mailto:eleqtholidays@gmail.com" className="text-amber-500">eleqtholidays@gmail.com</a></p>
                  <div className="pt-4 border-t border-white/10">
                    <p className="text-sm font-bold uppercase tracking-[0.2em] text-gray-400">Eleqt Holidays & Leisure</p>
                    <p className="text-sm text-gray-500">M/s Psynuxsoftware Pvt. Ltd.</p>
                  </div>
                </div>
              </section>

            </motion.div>
          </main>
        </div>
      </div>
      
      <div className="py-12 border-t border-gray-100 text-center">
        <p className="text-[10px] text-gray-400 font-bold uppercase tracking-[0.4em]">
          © 2026 ELEQT HOLIDAYS & LEISURE • OPERATED BY M/S PSYNUXSOFTWARE PVT LTD
        </p>
      </div>
    </div>
  );
}

export default TermsOfUse;
